import os
import re
import json


def load_contract_text(file_path):
    """
    Load the text generated by the document parser.
    """

    if not os.path.exists(file_path):
        raise FileNotFoundError(
            f"Contract text file not found:\n{file_path}"
        )

    with open(
        file_path,
        "r",
        encoding="utf-8"
    ) as file:

        text = file.read()

    return text


def extract_clauses(text):
    """
    Extract numbered contract clauses.

    Clauses are identified only when the clause number
    appears at the beginning of a sentence/section.
    """

    # Normalize whitespace while preserving enough structure
    text = re.sub(r'\s+', ' ', text).strip()

    # Contract clause pattern
    pattern = (
        r'(?<!\w)'
        r'(1[0-6]|[1-9])'
        r'\.\s+'
        r'([A-Z][A-Za-z &\-]+?)'
        r'\.\s+'
    )

    matches = list(re.finditer(pattern, text))

    clauses = []

    for i, match in enumerate(matches):

        clause_number = match.group(1)
        title = match.group(2).strip()

        start = match.end()

        if i + 1 < len(matches):
            end = matches[i + 1].start()
        else:
            end = len(text)

        clause_text = text[start:end].strip()

        if not clause_text:
            continue

        clauses.append(
            {
                "clause_number": clause_number,
                "title": title,
                "text": clause_text
            }
        )

    return clauses


def save_clauses(clauses, output_path):

    os.makedirs(
        os.path.dirname(output_path),
        exist_ok=True
    )

    with open(
        output_path,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            clauses,
            file,
            indent=4,
            ensure_ascii=False
        )


def print_clauses(clauses):

    print("\n" + "=" * 70)
    print("EXTRACTED CONTRACT CLAUSES")
    print("=" * 70)

    for clause in clauses:

        print(
            f"\nCLAUSE {clause['clause_number']}"
        )

        print(
            f"Title: {clause['title']}"
        )

        print(
            f"Text: {clause['text'][:300]}..."
        )

        print("-" * 70)


# --------------------------------------------------
# MAIN PROGRAM
# --------------------------------------------------

if __name__ == "__main__":

    print("=" * 70)
    print("CONTRACT CLAUSE EXTRACTOR")
    print("=" * 70)

    file_path = input(
        "\nEnter the path of the extracted TXT file: "
    ).strip()

    try:

        # Load contract
        text = load_contract_text(file_path)

        print(
            f"\nLoaded contract text: "
            f"{len(text)} characters"
        )

        # Extract clauses
        clauses = extract_clauses(text)

        print(
            f"\nNumber of clauses extracted: "
            f"{len(clauses)}"
        )

        # Display
        print_clauses(clauses)

        # Save JSON
        output_path = os.path.join(
            "data",
            "contracts",
            "extracted_clauses.json"
        )

        save_clauses(
            clauses,
            output_path
        )

        print("\nClauses saved to:")
        print(output_path)

        print("\n" + "=" * 70)
        print("CLAUSE EXTRACTION FINISHED")
        print("=" * 70)

    except Exception as e:

        print("\nERROR:")
        print(e)